[package]
name = "suture-elf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "TODO: describe suture-elf"


[dependencies]
goblin = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

